# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.0.0.1
group=com.wano.abysmol
java_version=21
minecraft_version=1.21.11
mod_name=ABYSMOL
mod_author=wanomaniac
mod_id=abysmol
license=CC0-1.0
credits=wanomaniac
description=ABYSMOL
modrinthID = qxv7rwef
modrinthTOKEN = USE_ENV VIA "mToken=TOKEN"
modrinthStatus = alpha
# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=false